// take an instance of createSlice method
import { createSlice } from "@reduxjs/toolkit";

// this createSlice method takes an object as argument and take 3 values: name , initialState, reducers which contain objects of reducer Functions ;

const initialState = {
  value: 1,
};

export const CounterSlice = createSlice({
  name: "counter", // name of the slice
  initialState, // initial state or the initial value of the slice
  reducers: {
    // functions will be using in the app
    increment: (state) => {
      //  the state parameter shows the initial state object
      state.value += 1;
    },
    decrement: (state) => {
      state.value -= 1;
    },
  },
});

// actions created for every reducer Function in a redux app

// export the reducer functions from Actions creators generated by createSlice method
export const { increment, decrement } = CounterSlice.actions;

// export the reducer to be used in store
export default CounterSlice.reducer; // always make the reducer a default export
